### ISSUE TITLE
jdk_switcher: "Sorry, but JDK 'oraclejdk10' is not known."

### ISSUE THREAD

**Issue by overheadhunter** [travis-ci/travis-cookbooks#989]
It seems like I can't switch back to oraclejdk10 in my build. Essentially I'm doing this:

```yml
language: java
sudo: false
jdk:
- oraclejdk10
script:
- # successfully compiling using jdk10
after_success:
- jdk_switcher use oraclejdk8
- # successfully doing stuff with jdk8
before_deploy:
- jdk_switcher use oraclejdk10 # ERROR
```

Switching back to JDK 10 results in an error:

```
$ jdk_switcher use oraclejdk10
Sorry, but JDK 'oraclejdk10' is not known.
The command "jdk_switcher use oraclejdk10" failed and exited with 1 during .
```

The full build log can be found [here](https://travis-ci.org/cryptomator/cryptomator/builds/402674565#L1373) and the full `.travis.yml` [here](https://github.com/cryptomator/cryptomator/blob/fe5ce7980271563033169bd8845e0f9686487413/.travis.yml).

---

Edit: Oops, I ended up in the wrong repo 🙈 Please can some admin move this to [travis-ci/travis-ci](https://github.com/travis-ci/travis-ci/issues/)? Sorry for that!
